/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HR;

import HR.addep;
import HR.edite;
import HR.Eregi;
import Admin.permission;
import woodworkshop.login;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.awt.image.ImageObserver.HEIGHT;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KAVI
 */
public class hr extends javax.swing.JFrame {

    /**
     * Creates new form hr
     */
    public hr() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(100, 100, (int) dim.getWidth(), (int) dim.getHeight());
        setLocationRelativeTo(null);
        dateTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btneregi = new javax.swing.JButton();
        btnelist = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblemployees = new javax.swing.JTable();
        txtsearch = new javax.swing.JTextField();
        btnEsearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtelist = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtdlist = new javax.swing.JTextArea();
        btndlist = new javax.swing.JButton();
        btnadddep = new javax.swing.JButton();
        btneedit = new javax.swing.JButton();
        btndedit = new javax.swing.JButton();
        btnlogout = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lbldate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rbtnepf = new javax.swing.JRadioButton();
        rbtnname = new javax.swing.JRadioButton();
        rbtnemail = new javax.swing.JRadioButton();
        rbtndep = new javax.swing.JRadioButton();
        rbtndes = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        btneregi.setText("Employee Registration form");
        btneregi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneregi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneregiActionPerformed(evt);
            }
        });
        jPanel2.add(btneregi);
        btneregi.setBounds(130, 190, 370, 30);

        btnelist.setText("List of Employees");
        btnelist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnelist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnelistActionPerformed(evt);
            }
        });
        jPanel2.add(btnelist);
        btnelist.setBounds(130, 330, 370, 30);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        jtblemployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jtblemployees);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(132, 70, 840, 100);
        jPanel2.add(txtsearch);
        txtsearch.setBounds(130, 30, 740, 30);

        btnEsearch.setText("Search");
        btnEsearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsearchActionPerformed(evt);
            }
        });
        jPanel2.add(btnEsearch);
        btnEsearch.setBounds(980, 30, 100, 30);

        txtelist.setColumns(20);
        txtelist.setRows(5);
        jScrollPane1.setViewportView(txtelist);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(130, 370, 370, 90);

        txtdlist.setColumns(20);
        txtdlist.setRows(5);
        jScrollPane2.setViewportView(txtdlist);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(710, 370, 370, 90);

        btndlist.setText("List of Departments");
        btndlist.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndlistActionPerformed(evt);
            }
        });
        jPanel2.add(btndlist);
        btndlist.setBounds(710, 330, 370, 30);

        btnadddep.setText("Add New Departments");
        btnadddep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnadddep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadddepActionPerformed(evt);
            }
        });
        jPanel2.add(btnadddep);
        btnadddep.setBounds(710, 190, 370, 30);

        btneedit.setText("Edit Employees");
        btneedit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneeditActionPerformed(evt);
            }
        });
        jPanel2.add(btneedit);
        btneedit.setBounds(130, 260, 370, 30);

        btndedit.setText("Edit Departments");
        btndedit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(btndedit);
        btndedit.setBounds(710, 260, 370, 30);

        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnlogout);
        btnlogout.setBounds(1000, 480, 80, 30);

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(881, 480, 80, 30);

        lbldate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbldate.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lbldateInputMethodTextChanged(evt);
            }
        });
        jPanel2.add(lbldate);
        lbldate.setBounds(130, 480, 370, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\PROJECTS\\woodWorkshop\\Images\\favpng_communication-consultant-management-consulting-business-cooperation.png")); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(350, 110, 500, 430);

        rbtnepf.setText("epf");
        rbtnepf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(rbtnepf);
        rbtnepf.setBounds(980, 70, 50, 23);

        rbtnname.setText("name");
        rbtnname.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(rbtnname);
        rbtnname.setBounds(980, 90, 80, 23);

        rbtnemail.setText("email");
        rbtnemail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(rbtnemail);
        rbtnemail.setBounds(980, 110, 80, 23);

        rbtndep.setText("department");
        rbtndep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(rbtndep);
        rbtndep.setBounds(980, 130, 100, 23);

        rbtndes.setText("designation");
        rbtndes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(rbtndes);
        rbtndes.setBounds(980, 150, 100, 23);

        jButton2.setText("Clear");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(883, 30, 90, 30);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setText("[]");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setText("-");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setUndecorated(true);
        this.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btneregiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneregiActionPerformed
        // TODO add your handling code here:
        new Eregi().toFront();
        new Eregi().setVisible(true);
    }//GEN-LAST:event_btneregiActionPerformed

    private void btnadddepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadddepActionPerformed
        // TODO add your handling code here:
        new addep().toFront();
        new addep().setVisible(true);
    }//GEN-LAST:event_btnadddepActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        this.toBack();
        this.setVisible(false);
        this.dispose();
        new login().toFront();
        new login().setVisible(true);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Object[] options= {"OK", "Cancel"};
        int response = JOptionPane.showOptionDialog(null, "sure you want to exit?", "Warning",JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
        
        if (response==JOptionPane.OK_OPTION)
        {
        System.exit(0);
        }
        else if(response==JOptionPane.CANCEL_OPTION)
                {
                
                }
        else if(response==JOptionPane.CLOSED_OPTION)
        {
        
        }
    }                                                                                    

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lbldateInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lbldateInputMethodTextChanged
        // TODO add your handling code here:
        dateTime();
    }//GEN-LAST:event_lbldateInputMethodTextChanged

    private void btnelistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnelistActionPerformed
        // TODO add your handling code here:
        String filename = "C:\\Users\\KAVI\\Desktop\\Employees.txt";

        try
        {
            FileReader reader = new FileReader(filename);
            BufferedReader br = new BufferedReader(reader);
            txtelist.read(br, null);
            br.close();
            txtelist.requestFocus();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnelistActionPerformed

    private void btneeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneeditActionPerformed
        // TODO add your handling code here:
        new edite().toFront();
        new edite().setVisible(true);
    }//GEN-LAST:event_btneeditActionPerformed

    private void btndlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndlistActionPerformed
        // TODO add your handling code here:
        String filename = "C:\\Users\\KAVI\\Desktop\\Departments.txt";

        try
        {
            FileReader reader = new FileReader(filename);
            BufferedReader br = new BufferedReader(reader);
            txtdlist.read(br, null);
            br.close();
            txtdlist.requestFocus();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btndlistActionPerformed

    private void btnEsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsearchActionPerformed
        // TODO add your handling code here:
        if(rbtnepf.isSelected())
        {
            this.userSearch(txtsearch.getText(), rbtnepf.getText(),0);
        }
        if(rbtnname.isSelected())
        {
            this.userSearch(txtsearch.getText(), rbtnname.getText(),1);
        }
        if(rbtnemail.isSelected())
        {
            this.userSearch(txtsearch.getText(), rbtnemail.getText(),2);
        }
        if(rbtndep.isSelected())
        {
            this.userSearch(txtsearch.getText(), rbtndep.getText(),3);
        }
        if(rbtndes.isSelected())
        {
            this.userSearch(txtsearch.getText(), rbtndes.getText(),4);
        }
    }//GEN-LAST:event_btnEsearchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtsearch.setText(null);
        jtblemployees.setValueAt(null, 0, 0);
        jtblemployees.setValueAt(null, 0, 1);
        jtblemployees.setValueAt(null, 0, 2);
        jtblemployees.setValueAt(null, 0, 3);
        jtblemployees.setValueAt(null, 0, 4);
        rbtnepf.setText(null);
        rbtnname.setText(null);
        rbtnemail.setText(null);
        rbtndep.setText(null);
        rbtndes.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEsearch;
    private javax.swing.JButton btnadddep;
    private javax.swing.JButton btndedit;
    private javax.swing.JButton btndlist;
    private javax.swing.JButton btneedit;
    private javax.swing.JButton btnelist;
    private javax.swing.JButton btneregi;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jtblemployees;
    private javax.swing.JLabel lbldate;
    private javax.swing.JRadioButton rbtndep;
    private javax.swing.JRadioButton rbtndes;
    private javax.swing.JRadioButton rbtnemail;
    private javax.swing.JRadioButton rbtnepf;
    private javax.swing.JRadioButton rbtnname;
    private javax.swing.JTextArea txtdlist;
    private javax.swing.JTextArea txtelist;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables

    public void dateTime()
    {
        ActionListener actiondate = new ActionListener()
        {
            
            @Override
            public void actionPerformed(ActionEvent e) {
                java.util.Date mydate = new Date();
                
                lbldate.setText("Time : "+mydate.getHours()+":"+mydate.getMinutes()+":"+mydate.getSeconds());
            }
        };
        new javax.swing.Timer(100, actiondate).start();
    }
    
    private void userSearch(String userDeatails, String Stype, int colnu)
      {
          //cat=String.valueOf(cmbCCatagory.getSelectedItem());
          DefaultTableModel mytblmodle=(DefaultTableModel)jtblemployees.getModel();
          mytblmodle.setRowCount(0);
          try
          {
            BufferedReader br = null;
            File file = new File("D:\\PROJECTS\\woodWorkshop\\files\\HR\\Employees.txt");
            FileReader fr = new FileReader(file); // java.io.FileReader
            br = new BufferedReader(fr); // java.io.BufferedReader
            String headingline = br. readLine().trim(); //read the file heading
            String[] colName=headingline.split("\\t");
            Object[] fileLines=br.lines().toArray();
            mytblmodle.setColumnIdentifiers(colName);
                for (int count=0;count<=fileLines.length-1;count++)
                {
                  String currentLine=fileLines[count].toString().trim();
                  String[] row=currentLine.split("\\t");

                  for (int x=0;x<=row.length-1;x++)
                  {          
                        if (row[colnu].equals(userDeatails)) 
                        {
                            JOptionPane.showMessageDialog(this, "User Found!","User Found!", HEIGHT);
                            mytblmodle.addRow(row);
                            break;
                        }
                    break;
                  }
                }
          }
          catch (FileNotFoundException ex) {
          JOptionPane.showMessageDialog(this, "Check selected User File!","User File Error", HEIGHT);
         // Logger.getLogger(frmHRM.class.getName()).log(Level.SEVERE, null, ex);
          }
          catch (IOException ex)
          {
         // Logger.getLogger(frmHRM.class.getName()).log(Level.SEVERE, null, ex);
          }
      }
}
