/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import java.awt.Dimension;
import java.awt.Toolkit;
import static java.awt.image.ImageObserver.HEIGHT;
import java.io.FileReader;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author KAVI
 */
public class resetAcc extends javax.swing.JFrame {

    /**
     * Creates new form resetAcc
     */
    public resetAcc() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        combnhint = new javax.swing.JComboBox<>();
        txtcuser = new javax.swing.JTextField();
        txthint = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtnuser = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnpwd = new javax.swing.JTextField();
        btnok = new javax.swing.JButton();
        btncancle = new javax.swing.JButton();
        combhint1 = new javax.swing.JComboBox<>();
        txtnhint = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel4.setText("Enter Current Username :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(50, 50, 150, 20);

        combnhint.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<select new hint>", "What is your hobby?", "What is your chilhood name?", "What is your father's name?", "What is your primary school?", "What is your girl friend's name?" }));
        jPanel2.add(combnhint);
        combnhint.setBounds(50, 250, 220, 30);
        jPanel2.add(txtcuser);
        txtcuser.setBounds(290, 50, 210, 30);
        jPanel2.add(txthint);
        txthint.setBounds(290, 100, 210, 30);

        jLabel5.setText("Enter New Username :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(50, 150, 150, 30);
        jPanel2.add(txtnuser);
        txtnuser.setBounds(290, 150, 210, 30);

        jLabel6.setText("Enter New Password :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(50, 200, 170, 30);
        jPanel2.add(txtnpwd);
        txtnpwd.setBounds(290, 200, 210, 30);

        btnok.setText("OK");
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });
        jPanel2.add(btnok);
        btnok.setBounds(427, 290, 70, 23);

        btncancle.setText("Cancle");
        btncancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancleActionPerformed(evt);
            }
        });
        jPanel2.add(btncancle);
        btncancle.setBounds(290, 290, 73, 23);

        combhint1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<select current hint>", "What is your hobby?", "What is your chilhood name?", "What is your father's name?", "What is your primary school?", "What is your girl friend's name?" }));
        jPanel2.add(combhint1);
        combhint1.setBounds(50, 100, 220, 30);
        jPanel2.add(txtnhint);
        txtnhint.setBounds(290, 250, 210, 30);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setText("[]");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setText("-");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        jLabel7.setText("RESET");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 427, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.toBack();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setUndecorated(true);
        this.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btncancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancleActionPerformed
        // TODO add your handling code here:
        this.toBack();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_btncancleActionPerformed

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        // TODO add your handling code here:
        String cUname = txtcuser.getText();
        String chint = combhint1.getSelectedItem().toString();
        String Chint = txthint.getText();
        String nUname = txtnuser.getText();
        String nPwd = txtnpwd.getText();
        String nhint = combnhint.getSelectedItem().toString();
        String Nhint = txtnhint.getText();
        
        ArrayList<String> tempArray = new ArrayList<>();
        
        try
        {
            try(FileReader fr = new FileReader("C:\\Users\\KAVI\\Desktop\\AdminPermission.txt"))
            {
                Scanner reader = new Scanner(fr);
                String line;
                String[] lineArr;
                
                while((line=reader.nextLine())!=null)
                {
                    lineArr = line.split("\t");
                    if(lineArr[0].equals(cUname))
                    {
                        tempArray.add(
                        nUname + "\t" +
                        nPwd + "\t" +
                        nhint + "\t" +
                        Nhint);
                        
                    }else
                    {
                        tempArray.add(line);
                    }
                }
                fr.close();
            }catch(Exception e)
            {
                
            }
        }catch(Exception e)
                {
                    
                }
        try
        {
            try(PrintWriter pr = new  PrintWriter("C:\\Users\\KAVI\\Desktop\\AdminPermission.txt"))
            {
                for(String str : tempArray)
                {
                    pr.println(str);
                }
                pr.close();
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "Update sucess", "sucess", HEIGHT);
                txtcuser.setText(null);
                combhint1.setSelectedItem(1);
                txthint.setText(null);
                txtnuser.setText(null);
                txtnpwd.setText(null);
                combnhint.setSelectedItem(1);
                txtnhint.setText(null);
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Something went wrong!!", "failture", HEIGHT);
        }
    }//GEN-LAST:event_btnokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(resetAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(resetAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(resetAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(resetAcc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new resetAcc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancle;
    private javax.swing.JButton btnok;
    private javax.swing.JComboBox<String> combhint1;
    private javax.swing.JComboBox<String> combnhint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtcuser;
    private javax.swing.JTextField txthint;
    private javax.swing.JTextField txtnhint;
    private javax.swing.JTextField txtnpwd;
    private javax.swing.JTextField txtnuser;
    // End of variables declaration//GEN-END:variables
}
